[workspace]
resolver = "2"
members = [
    "mspm0-data-types",
    "mspm0-metapac-gen",
    # "mspm0-metapac",
    "mspm0-data-gen",
]
exclude = [
    "build"
]

[workspace.dependencies]
anyhow = "1.0.89"
chiptool = { git = "https://github.com/embassy-rs/chiptool", rev = "bcf538a2e7b8584ae874ee9ab72efb1576fc6152" }
glob = "0.3.1"
heck = "0.5.0"
quote = "1.0.37"
lopdf = "0.34.0"
prettyplease = "0.2.31"
regex = "1.11.0"
serde = "1.0.210"
serde_json = "1.0.128"
# Pinned to match chiptool, which requires this exact version.
serde_yaml = "=0.9.34-deprecated"
syn = { version = "2.0.119", features = ["full", "parsing"] }
proc-macro2 = "1.0.86"
walkdir = "2.5.0"

# Optimize for dev experience: shortest "build+run" time after making a small change.
[profile.release]
debug = true
incremental = true
panic = 'abort'
opt-level = 2
