use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use anyhow::Context;
use mspm0_data_types::{Chip, Package};
use proc_macro2::Literal;
use quote::quote;

mod interrupt;
mod krate;
mod linker;
mod metadata;
mod peripheral;
mod registers;

const AUTOGENERATED_TEXT: &str =
    "// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.";

fn main() -> anyhow::Result<()> {
    let mut chips = BTreeMap::new();
    let out_dir = PathBuf::from("build/mspm0-metapac");
    fs::create_dir_all(&out_dir)?;

    for f in glob::glob("build/data/*.json")?.flatten() {
        let name = f
            .file_name()
            .context("chip data file has no name")?
            .to_string_lossy()
            .replace(".json", "")
            .to_lowercase();

        let chip: Chip = serde_json::from_str(&fs::read_to_string(&f).unwrap())
            .context(format!("Error reading chip: {}", name))?;
        chips.insert(name, chip);
    }

    // First because it creates `src/`, which krate::generate copies lib.rs into. It no longer has
    // to precede the PAC for the formatter's sake: rustfmt followed `mod` declarations into files
    // that did not exist yet, and prettyplease parses each file on its own.
    registers::generate(&out_dir)?;

    let mut metadata_dedup = BTreeMap::new();
    let mut all_peripheral_versions = BTreeMap::new();

    for (name, chip) in &mut chips {
        for package in chip.packages.iter() {
            let name = format!("{name}{}", package.package.to_lowercase());

            generate_chip_pac(&name, chip, &out_dir, &mut all_peripheral_versions);
            generate_chip_metadata(&name, chip, package, &out_dir, &mut metadata_dedup);

            linker::generate_device_x(&name, chip, &out_dir)?;
            linker::generate_memory_x(&name, chip, &out_dir)?;
        }
    }

    generate_all_chips(&out_dir, chips.values())?;
    generate_all_peripheral_versions(&out_dir, &all_peripheral_versions)?;

    krate::generate(&out_dir, &chips)?;

    Ok(())
}

fn generate_chip_pac(
    name: &str,
    chip: &Chip,
    out_dir: &Path,
    all_peripheral_versions: &mut BTreeMap<String, BTreeSet<String>>,
) {
    let chips = out_dir.join("src/chips");
    fs::create_dir_all(&chips).unwrap();

    let chip_dir = chips.join(name);
    fs::create_dir_all(&chip_dir).unwrap();

    let interrupts = interrupt::generate(chip);
    let peripherals = peripheral::generate(chip, all_peripheral_versions);

    write_rust(
        chip_dir.join("pac.rs"),
        &quote!(#interrupts #peripherals).to_string(),
    )
    .unwrap();
}

fn generate_chip_metadata(
    name: &str,
    chip: &Chip,
    package: &Package,
    out_dir: &Path,
    metadata_dedup: &mut BTreeMap<String, String>,
) {
    let chips_dir = out_dir.join("src/chips");
    let dir = chips_dir.join(name);
    fs::create_dir_all(&dir).unwrap();

    let mut data = String::new();
    write!(
        &mut data,
        "
        pub(crate) static PERIPHERALS: &[Peripheral] = {};
        pub(crate) static INTERRUPTS: &[Interrupt] = {};
        pub(crate) static INTERRUPT_GROUPS: &[InterruptGroup] = {};
        pub(crate) static DMA_CHANNELS: &[DmaChannel] = {};
        pub(crate) static PINS: &[Pin] = {};
        ",
        metadata::peripherals(chip, package),
        metadata::interrupts(chip),
        metadata::interrupt_groups(chip),
        metadata::dma_channels(chip),
        metadata::pins(chip, package),
    )
    .unwrap();

    let n = metadata_dedup.len();
    let deduped_file = metadata_dedup.entry(data.clone()).or_insert_with(|| {
        let file = format!("metadata_{:04}.rs", n);
        let path = chips_dir.join(&file);

        write_rust(&path, &data).unwrap();

        file
    });

    let family = &chip.family;
    let adc_memctl = Literal::u8_unsuffixed(chip.adc_memctl);
    let adc_vrsel = Literal::u8_unsuffixed(chip.adc_vrsel);
    let include = format!("../{deduped_file}");

    let contents = quote! {
        include!(#include);

        pub static METADATA: Metadata = Metadata {
            name: #name,
            family: #family,
            peripherals: PERIPHERALS,
            pins: PINS,
            interrupts: INTERRUPTS,
            interrupt_groups: INTERRUPT_GROUPS,
            dma_channels: DMA_CHANNELS,
            adc_memctl: #adc_memctl,
            adc_vrsel: #adc_vrsel,
        };
    }
    .to_string();

    write_rust(dir.join("metadata.rs"), &contents).unwrap();
}

fn generate_all_chips<'a>(
    out_dir: &Path,
    chips: impl Iterator<Item = &'a Chip>,
) -> anyhow::Result<()> {
    let mut list = Vec::new();

    for chip in chips {
        for package in chip.packages.iter() {
            list.push(&package.chip);
        }
    }

    let list = quote! {
        pub const ALL_CHIPS: &[&str] = &[
            #(#list),*
        ];
    };

    write_rust(out_dir.join("src/all_chips.rs"), &list.to_string())
}

fn generate_all_peripheral_versions(
    out_dir: &Path,
    all_versions: &BTreeMap<String, BTreeSet<String>>,
) -> anyhow::Result<()> {
    let mut contents = String::new();
    writeln!(
        &mut contents,
        "pub static ALL_PERIPHERAL_VERSIONS: &[(&str, &[&str])] = &["
    )?;
    for (kind, versions) in all_versions.iter() {
        write!(&mut contents, "    ({:?}, &[", kind)?;
        for version in versions.iter() {
            write!(&mut contents, "{:?}, ", version)?;
        }
        writeln!(&mut contents, "]),")?;
    }
    writeln!(&mut contents, "];")?;

    write_rust(out_dir.join("src/all_peripheral_versions.rs"), &contents)
}

/// Write generated Rust to `path`, formatted, with the autogenerated banner on top.
///
/// prettyplease rather than rustfmt: this binary writes about five hundred files, and spawning
/// rustfmt once per file was 95% of its runtime — 32 seconds of 34. Formatting in-process also
/// drops an undeclared dependency on rustfmt being installed.
///
/// The banner is prepended after formatting because `syn` keeps only doc comments, so a `//` line
/// would not survive the round trip. Rust allows a comment ahead of the inner attributes that some
/// of these files open with.
pub fn write_rust(path: impl AsRef<Path>, contents: &str) -> anyhow::Result<()> {
    let path = path.as_ref();
    let parsed = syn::parse_file(contents)
        .with_context(|| format!("generated Rust for {} does not parse", path.display()))?;

    fs::write(
        path,
        format!("{AUTOGENERATED_TEXT}\n{}", prettyplease::unparse(&parsed)),
    )
    .with_context(|| format!("writing {}", path.display()))?;

    Ok(())
}
