"""Extract the functional advisory table from MSPM0 errata sheets.

Which errata apply to a device is not derivable from anything else, and getting it wrong is quiet:
the symptom of a missing workaround is a device that mostly works. This writes
`data/errata/<family>.yaml`.

Like `tools/operating_modes.py`, this is an offline aid rather than part of the build. Re-run it after
a data source bump rather than editing the YAML by hand.

Usage:
    uv run tools/errata.py <errata.pdf> [...]      # print the table
    uv run tools/errata.py --write <dir-of-pdfs>   # regenerate data/errata

`uv run` installs the dependencies below on its own; a bare `python` needs them on the path.

Only section 1, "Functional Advisories", is read: TI defines those as the ones which "affect the
device's operation, function, or parametrics", which is the set a driver has to work around. The
sheets also carry preprogrammed-software, debug-only and fixed-by-compiler advisories, and those
sections start on the same pages, so tables are matched to their caption rather than taken in order.

Each column of the table is a silicon revision. A device is reported as affected when **any** revision
is, since a driver built for a part has to run on whichever revision it meets.
"""

# /// script
# requires-python = ">=3.10"
# dependencies = ["pdfplumber", "pyyaml"]
# ///

import re
import sys
from collections.abc import Iterator
from pathlib import Path

try:
    import pdfplumber
    import yaml
except ImportError as e:  # pragma: no cover
    raise SystemExit(f"{e.name} is missing; run this with `uv run` instead of `python`")

SECTION = "Functional Advisories"

#: A numbered top-level section heading, as distinct from the "Table 1-1. Functional Advisories
#: (continued)" caption which repeats the title, and from the dotted table-of-contents entry.
#:
#: The section's number is not fixed: SLAZ741 numbers its advisory sections 2 to 5 where the others
#: use 1 to 4, so the title is what identifies it. Not every advisory table has a caption at all --
#: the debug-only table of SLAZ742 does not -- so the headings are what the sections are told apart by.
HEADING = re.compile(r"^\d+\s+(?P<title>[A-Z][A-Za-z][A-Za-z ]*[a-z])$")

LATTICE = {"vertical_strategy": "lines", "horizontal_strategy": "lines"}

#: An errata identifier. `CRC/CRCP_ERR_01` is one row naming two peripherals.
ERRATUM = re.compile(r"^(?P<peripherals>[A-Z0-9]+(?:/[A-Z0-9]+)*)_ERR_(?P<number>\d+)$")

#: A cell saying the revision in that column is affected.
AFFECTED = ("✓", "✔", "yes")


def read_tables(path: Path) -> Iterator[set[str]]:
    """Yield the errata named by each table inside the functional advisory section.

    The later advisory sections start partway down a page the functional one also uses, so each table
    is placed by the last section heading above it, tracked across pages. The section runs until the
    next heading, so reading stops there rather than continuing into the per-erratum descriptions --
    those have `Errata Number` tables of their own.
    """
    inside = False

    with pdfplumber.open(str(path)) as pdf:
        for page in pdf.pages:
            headings = [
                (line["bottom"], HEADING.match(line["text"].strip())["title"])
                for line in page.extract_text_lines()
                if HEADING.match(line["text"].strip())
            ]
            tables = [(table.bbox[1], table) for table in page.find_tables(LATTICE)]

            # Walk the page top to bottom so a heading applies to the tables which follow it.
            for _, item in sorted(headings + tables, key=lambda entry: entry[0]):
                if isinstance(item, str):
                    if inside and item != SECTION:
                        return
                    inside = item == SECTION
                elif inside:
                    yield read_table(item.extract())


def read_table(table: list[list[str | None]]) -> set[str]:
    """Errata in one table which affect at least one silicon revision."""
    if not table or not table[0] or (table[0][0] or "").strip() != "Errata Number":
        return set()

    affected = set()
    for row in table[1:]:
        name = (row[0] or "").replace("\n", "").strip()
        match = ERRATUM.match(name)
        if not match:
            continue

        # Every column after the first is one silicon revision.
        if not any((cell or "").strip().lower() in AFFECTED for cell in row[1:]):
            continue

        number = match["number"]
        affected.update(f"{p}_ERR_{number}" for p in match["peripherals"].split("/"))

    return affected


HEADER = """\
# Errata which apply to this family, by TI's identifier.
#
# GENERATED by `tools/errata.py --write` from section 1, "Functional Advisories", of {doc}.
# Re-run the tool rather than editing by hand.
#
# An erratum is listed when any silicon revision is affected, since a driver built for a part has to
# run on whichever revision it meets.
"""


def write(pdfs: str) -> int:
    """Regenerate data/errata/*.yaml. Returns the number of problems reported."""
    parts = yaml.safe_load(Path("data/parts.yaml").read_text(encoding="utf-8"))
    families = [(f["family"], f["errata_url"].rsplit("/", 1)[-1]) for f in parts["families"]]

    Path("data/errata").mkdir(parents=True, exist_ok=True)
    problems = 0

    for family, doc in families:
        pdf = Path(pdfs) / f"{doc}_errata.pdf"
        if not pdf.exists():
            print(f"{family}: no errata sheet for {doc} in {pdfs}")
            problems += 1
            continue

        errata: set[str] = set()
        for table in read_tables(pdf):
            errata |= table

        if not errata:
            print(f"{family}: no functional advisories found in {pdf.name}")
            problems += 1
            continue

        body = "".join(f"- {name}\n" for name in sorted(errata))
        path = Path(f"data/errata/{family}.yaml")
        with open(path, "w", encoding="utf-8", newline="\n") as out:
            out.write(HEADER.format(doc=doc.upper()) + "\n" + body)
        print(f"{family}: {len(errata)} errata, from {pdf.name}")

    return problems


def main(argv: list[str]) -> None:
    if "--write" in argv:
        i = argv.index("--write")
        raise SystemExit(1 if write(argv[i + 1] if i + 1 < len(argv) else ".") else 0)

    paths = [Path(a) for a in argv if not a.startswith("--")]
    if not paths:
        raise SystemExit(__doc__)

    for path in paths:
        print(f"########## {path.name}")
        errata: set[str] = set()
        for table in read_tables(path):
            errata |= table
        print("    " + " ".join(sorted(errata)))


if __name__ == "__main__":
    main(sys.argv[1:])
