"""Extract the VREF startup time from MSPM0 datasheets.

`VREF.CTL0.ENABLE` starts a reference buffer and `CTL1.READY` is supposed to say when it has settled,
but `VREF_ERR_01` leaves that bit set once a buffer has been enabled a first time since reset. On an
affected device -- 93 of them -- the datasheet's `Tstartup` is the only way to know the reference is
usable, so TI's own workaround is to wait it out. This writes `data/vref/<family>.yaml`.

Like `tools/wakeup.py`, this is an offline aid rather than part of the build. Re-run it after a data
source bump rather than editing the YAML by hand.

Usage:
    uv run tools/vref.py <datasheet.pdf> [...]      # print what it finds
    uv run tools/vref.py --write <dir-of-datasheets> # regenerate data/vref

`uv run` installs the dependencies below on its own; a bare `python` needs them on the path.

Two things about the row are worth knowing:

- **The figure spans MIN, TYP and MAX**, as the wake-up times do, so it is a typical value rather than
  a guaranteed ceiling. A consumer needing margin has to add its own.
- **The stated conditions differ between datasheets** -- `VDD = 2.8 V` on most, `2.7 V` on the C1104 --
  and one figure per device is therefore a simplification. The conditions are written into the
  generated file's header so the simplification is visible rather than implied.
"""

# /// script
# requires-python = ">=3.10"
# dependencies = ["pdfplumber", "pypdfium2", "pyyaml"]
# ///

import re
import sys
from collections.abc import Iterator
from pathlib import Path

try:
    import pdfplumber
    import pypdfium2
    import yaml
except ImportError as e:  # pragma: no cover
    raise SystemExit(f"{e.name} is missing; run this with `uv run` instead of `python`")

CAPTION = "VREF startup time"

LATTICE = {"vertical_strategy": "lines", "horizontal_strategy": "lines"}

#: Time units the figure may be given in, as a multiplier to nanoseconds. The datasheets are
#: inconsistent about the case of the SI prefix, hence the lowercasing before lookup.
UNITS = {"ns": 1, "us": 1_000, "µs": 1_000, "ms": 1_000_000}

NUMBER = re.compile(r"\d+(?:\.\d+)?")


def caption_pages(path: Path) -> list[int]:
    """Indices of the pages carrying the VREF electrical table."""
    doc = pypdfium2.PdfDocument(str(path))
    try:
        return [i for i in range(len(doc)) if CAPTION in doc[i].get_textpage().get_text_range()]
    finally:
        doc.close()


def read_tables(path: Path) -> Iterator[tuple[int, str]]:
    """Yield `(startup time in ns, conditions)` for each VREF startup row found."""
    for page_index in caption_pages(path):
        with pdfplumber.open(str(path)) as pdf:
            for table in pdf.pages[page_index].extract_tables(LATTICE):
                for row in table:
                    cells = [(c or "").replace("\n", " ").strip() for c in row]
                    if not any(CAPTION in cell for cell in cells):
                        continue

                    found = read_row(cells)
                    if found is not None:
                        yield found


def read_row(cells: list[str]) -> tuple[int, str] | None:
    """Read one `Tstartup` row into nanoseconds, or `None` if it does not parse.

    The row is symbol, description, conditions, the MIN/TYP/MAX columns and a unit. Only one of the
    three figure columns is filled, so the first bare number after the caption is the figure wherever
    the table puts it.
    """
    unit = next((c for c in reversed(cells) if c and c.lower() in UNITS), "")
    if not unit:
        return None

    caption_at = next(i for i, cell in enumerate(cells) if CAPTION in cell)

    # Conditions may share the caption's cell or sit in the next one; either way they are the text
    # between the caption and the first figure.
    conditions = ""
    value = None
    for cell in cells[caption_at:]:
        stripped = cell.replace(CAPTION, "").strip()
        if NUMBER.fullmatch(stripped):
            value = float(stripped)
            break
        if stripped:
            conditions = f"{conditions} {stripped}".strip()

    if value is None:
        return None

    return round(value * UNITS[unit.lower()]), undouble(" ".join(conditions.split()))


def undouble(text: str) -> str:
    """Collapse a condition string the extractor read twice.

    The C1104's table returns its condition cell doubled -- `BUFCONFIG = {0, 1} , VDD = 2.7 V` twice
    over -- where the other datasheets return it once. Only the text repeats; the figure beside it is
    read correctly either way.
    """
    words = text.split()
    half = len(words) // 2
    if words and len(words) % 2 == 0 and words[:half] == words[half:]:
        return " ".join(words[:half])

    return text


HEADER = """\
# How long this family's VREF takes to settle after CTL0.ENABLE, in nanoseconds.
#
# GENERATED by `tools/vref.py --write` from the `Tstartup` row of the {ds} datasheet.
# Re-run the tool rather than editing by hand.
#
# The figure's cell spans the datasheet's MIN, TYP and MAX columns, so it is typical rather than a
# guaranteed ceiling. It is stated under one set of conditions, quoted here, and recorded as one
# number per family because that is all the source gives:
#
#   {conditions}
"""


def write(datasheets: str) -> int:
    """Regenerate data/vref/*.yaml. Returns the number of problems reported."""
    parts = yaml.safe_load(Path("data/parts.yaml").read_text(encoding="utf-8"))
    families = [(f["family"], f["datasheet_url"].rsplit("/", 1)[-1]) for f in parts["families"]]

    Path("data/vref").mkdir(parents=True, exist_ok=True)
    problems = 0

    for family, gpn in families:
        pdf = Path(datasheets) / f"{gpn}_datasheet.pdf"
        if not pdf.exists():
            print(f"{family}: no datasheet for {gpn} in {datasheets}")
            problems += 1
            continue

        found = list(read_tables(pdf))
        if not found:
            print(f"{family}: no VREF startup time in {pdf.name}")
            problems += 1
            continue

        # A datasheet may state the row under several conditions -- the G5187 gives 20us bare and
        # 200us with the 1uF capacitor on VREF+ -- and the slowest is the one worth planning around,
        # since waiting too long only costs time. Every condition is quoted so the choice is visible.
        ns, conditions = max(found, key=lambda f: f[0])
        if len({value for value, _ in found}) > 1:
            others = "; ".join(f"{v / 1000:g}us at {c}" for v, c in sorted(found))
            conditions = f"{conditions}\n#\n#   slowest of: {others}"

        path = Path(f"data/vref/{family}.yaml")
        with open(path, "w", encoding="utf-8", newline="\n") as out:
            out.write(HEADER.format(ds=gpn.upper(), conditions=conditions or "none stated"))
            out.write(f"\nstartup_ns: {ns}\n")
        print(f"{family}: {ns / 1000:g} us, from {pdf.name}")

    return problems


def main(argv: list[str]) -> None:
    if "--write" in argv:
        i = argv.index("--write")
        raise SystemExit(1 if write(argv[i + 1] if i + 1 < len(argv) else ".") else 0)

    paths = [Path(a) for a in argv if not a.startswith("--")]
    if not paths:
        raise SystemExit(__doc__)

    for path in paths:
        print(f"########## {path.name}")
        for ns, conditions in read_tables(path):
            print(f"    {ns / 1000:>8g} us   {conditions}")


if __name__ == "__main__":
    main(sys.argv[1:])
